In [1]:
import pandas as pd

In [2]:
s = pd.Series([10,20,30,40,50])
print(s)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [4]:
data={
    "name":["jeba","yamu","swe"],"age":[19,17,15],"marks":[90,85,95]}

In [5]:
df=pd.DataFrame(data)

In [6]:
print(df)

   name  age  marks
0  jeba   19     90
1  yamu   17     85
2   swe   15     95

In [7]:
df.head()

   name  age  marks
0  jeba   19     90
1  yamu   17     85
2   swe   15     95

In [8]:
df.tail()

   name  age  marks
0  jeba   19     90
1  yamu   17     85
2   swe   15     95

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      object
 1   age     3 non-null      int64
 2   marks   3 non-null      int64
dtypes: int64(2), object(1)
memory usage: 204.0+ bytes

In [10]:
df.describe()

        age  marks
count   3.0    3.0
mean   17.0   90.0
std     2.0    5.0
min    15.0   85.0
25%    16.0   87.5
50%    17.0   90.0
75%    18.0   92.5
max    19.0   95.0

In [11]:
print(df.columns)

Index(['name', 'age', 'marks'], dtype='object')

In [12]:
print(df["name"])

0    jeba
1    yamu
2     swe
Name: name, dtype: object

In [14]:
print(df[["name","marks"]])

   name  marks
0  jeba     90
1  yamu     85
2   swe     95

In [15]:
print(df.iloc[1])

name     yamu
age        17
marks      85
Name: 1, dtype: object

In [16]:
print(df[df["marks"]>90])

  name  age  marks
2  swe   15     95

In [17]:
df.sort_values("marks")

   name  age  marks
1  yamu   17     85
0  jeba   19     90
2   swe   15     95

In [18]:
df.sort_values("marks",ascending=False)

   name  age  marks
2   swe   15     95
0  jeba   19     90
1  yamu   17     85

In [19]:
df.dropna()

   name  age  marks
0  jeba   19     90
1  yamu   17     85
2   swe   15     95